#!/bin/bash
# ZAKAT DONOR FORM - IMPLEMENTATION CHECKLIST
# This script helps verify the implementation status and requirements

echo "🕌 Zakat Donor Form Implementation Checklist"
echo "==========================================="
echo ""

echo "✅ FRONTEND IMPLEMENTATION STATUS:"
echo "   [✓] Updated ZakatCalculator.tsx with comprehensive form"
echo "   [✓] Extended ZakatTransaction interface"
echo "   [✓] Implemented all form sections"
echo "   [✓] Added conditional field rendering"
echo "   [✓] Added form validation logic"
echo "   [✓] Styled form with Tailwind CSS"
echo ""

echo "📋 BACKEND REQUIREMENTS (MUST IMPLEMENT):"
echo ""

echo "1. UPDATE MongoDB Schema:"
echo "   Location: backend/src/models/ZakatPayment.ts"
echo "   Action: Update schema to include all new fields (see ZAKAT_BACKEND_MODEL_SAMPLE.ts)"
echo "   Fields to add:"
echo "     - Basic Information: contactNumber, email, address, donorType enum"
echo "     - Zakat Details: zakatType, currency, hijriYear"
echo "     - Payment Status: paymentStatus"
echo "     - Conditional Fields: upiTransactionId, bankName, ifscCode, transferDateTime, etc."
echo "     - Additional: notes, recurringDonation, nisabVerified, anonymousDonation, taxReceiptRequired, allocationCategory"
echo ""

echo "2. UPDATE API ENDPOINTS (backend/src/routes/zakat.ts):"
echo "   POST /zakat/transaction"
echo "     └─ Add validation for conditional required fields"
echo "     └─ Validate donor information based on donorType"
echo "     └─ Handle anonymousDonation flag"
echo ""
echo "   PUT /zakat/payment/:id"
echo "     └─ Update all new fields"
echo "     └─ Same validation as POST"
echo ""
echo "   GET /zakat/payments"
echo "     └─ Return all new fields in response"
echo "     └─ Add filtering support (by zakatType, allocationCategory, hijriYear, etc.)"
echo "     └─ Add sorting support"
echo ""
echo "   GET /zakat/stats"
echo "     └─ Update stats calculation to include new fields"
echo "     └─ Add breakdown by allocationCategory"
echo "     └─ Add breakdown by zakatType"
echo "     └─ Add breakdown by hijriYear"
echo ""
echo "   GET /zakat/donors (optional - already implemented in frontend)"
echo "     └─ Update to exclude anonymousDonation entries"
echo ""

echo "3. DATA VALIDATION RULES"
echo ""
echo "   Conditional Required Fields:"
echo "   IF donorType !== 'Anonymous' AND type === 'Credit':"
echo "     - contactNumber OR email must be provided"
echo ""
echo "   Payment Method Dependent Fields:"
echo "   - UPI Transfer: upiId *, upiTransactionId *"
echo "   - Bank Transfer: bankName *, accountNumberLast4 *, ifscCode *, transferDateTime *"
echo "   - Cash: collectedBy *, collectionLocation *, receiptNumber *"
echo "   - Cheque: chequeNumber *, bankName *, chequeDate *, clearanceStatus *"
echo "   - Card/Online Gateway: gatewayName *, gatewayTransactionId *"
echo ""
echo "   (* = required when payment method is selected)"
echo ""

echo "4. OPTIONAL ENHANCEMENTS"
echo "   [ ] Generate auto-numbered receipts for cash transactions"
echo "   [ ] Generate 80G tax receipts when taxReceiptRequired = true"
echo "   [ ] Implement recurring donation automation"
echo "   [ ] Add currency conversion for non-INR donations"
echo "   [ ] Send email acknowledgments to donors"
echo "   [ ] Generate donor donor statistics dashboard"
echo ""

echo "📝 TESTING CHECKLIST:"
echo ""
echo "Frontend Tests:"
echo "[ ] Create Credit transaction with all fields"
echo "[ ] Create Debit transaction"
echo "[ ] Test Anonymous donor toggle (disables name field)"
echo "[ ] Test conditional field visibility for each payment method"
echo "[ ] Test form validation (contact/email required for non-anonymous)"
echo "[ ] Test recurring donation frequency selector"
echo "[ ] Test edit transaction modal (pre-fills all fields)"
echo "[ ] Test allocation category dropdown"
echo "[ ] Verify Nisab checkbox behavior"
echo "[ ] Test tax receipt checkbox"
echo ""

echo "Backend Tests:"
echo "[ ] POST /zakat/transaction with UPI fields"
echo "[ ] POST /zakat/transaction with Bank Transfer fields"
echo "[ ] POST /zakat/transaction with Cash fields"
echo "[ ] POST /zakat/transaction with Cheque fields"
echo "[ ] POST /zakat/transaction with Card/Gateway fields"
echo "[ ] Verify validation rejects incomplete conditional fields"
echo "[ ] Verify anonymous donations hide donor name"
echo "[ ] PUT /zakat/payment/:id updates all fields"
echo "[ ] GET /zakat/payments returns all fields"
echo "[ ] GET /zakat/stats includes category breakdown"
echo ""

echo "Integration Tests:"
echo "[ ] Submit form → Verify data in database"
echo "[ ] Edit transaction → Verify updates"
echo "[ ] Check transaction history displays all fields"
echo "[ ] Verify donor summary aggregation works"
echo "[ ] Test filtering and sorting by new fields"
echo ""

echo "🔐 SECURITY CONSIDERATIONS:"
echo ""
echo "[ ] Sanitize all text inputs (prevent XSS)"
echo "[ ] Validate email format server-side"
echo "[ ] Validate phone number format server-side"
echo "[ ] Mask sensitive data:"
echo "    - Credit card: Show only last 4 digits (X's for rest)"
echo "    - Bank account: Show only last 4 digits"
echo "    - UPI: Don't log full UPI in error messages"
echo "[ ] Implement rate limiting on form submission"
echo "[ ] Use helmet.js for security headers"
echo "[ ] Validate amount > 0 before processing"
echo "[ ] Ensure authenticated endpoints check user roles"
echo ""

echo "📊 DATABASE MIGRATION:"
echo ""
echo "For existing zakat_payments collection:"
echo "[ ] Create migration script to add new fields (set defaults)"
echo "[ ] Backfill currency field with 'INR' for existing records"
echo "[ ] Backfill allocationCategory with 'General' for existing records"
echo "[ ] Ensure uniqueness constraints on paymentId and receiptNumber"
echo "[ ] Add database indexes for common queries"
echo ""

echo "🚀 DEPLOYMENT STEPS:"
echo ""
echo "1. Update backend model and validation"
echo "2. Deploy database migration"
echo "3. Test backend endpoints with new fields"
echo "4. Verify frontend is using latest API"
echo "5. Test end-to-end workflow"
echo "6. Deploy to production"
echo "7. Monitor error logs for validation issues"
echo ""

echo "📞 SUPPORT FEATURES TO CONSIDER:"
echo ""
echo "[ ] Help text tooltips for complex fields"
echo "[ ] Example formats for phone numbers and account numbers"
echo "[ ] User guide for different payment methods"
echo "[ ] FAQ about Zakat types and allocation categories"
echo "[ ] Export transaction data to CSV"
echo "[ ] Print receipt functionality"
echo ""

echo "✨ Implementation Status: FRONTEND COMPLETE ✓"
echo "⏳ Waiting for: Backend Model Update & API Endpoints"
echo ""
echo "For detailed documentation, see:"
echo "  - ZAKAT_DONOR_FORM_IMPLEMENTATION.md"
echo "  - ZAKAT_BACKEND_MODEL_SAMPLE.ts"
echo ""
